# Generated by Django 4.2.3 on 2023-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengadaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bagian', models.CharField(max_length=16)),
                ('nomor_spk', models.CharField(max_length=32)),
                ('vendor', models.CharField(max_length=128)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('uraian', models.TextField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('basket', models.CharField(max_length=16)),
                ('status_approval', models.BooleanField(default=False)),
                ('status_bayar', models.CharField(max_length=8)),
            ],
        ),
    ]
