# Generated by Django 4.2.3 on 2023-07-18 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_pengadaan_bagian_alter_pengadaan_uraian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keuangan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='status_bayar',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='a3c_150',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='a3c_240',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='air_insulated_cbom',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='air_insulated_pb',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='fully_insulated_cbom',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='fully_insulated_lbs',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='fully_insulated_pb',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='jtr_rak_tr',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='jtr_sktr',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_cell_vt',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_incoming',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_kopel',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_outgoing',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_ps',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kubikel_gi_riser',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kwh_1_phase_prabayar',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kwh_1_phase_reguler',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kwh_amr_3_phase_besar',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kwh_amr_3_phase_tm',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='kwh_elektrik_3_phase_kecil',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_100',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_150',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_200',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_250',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_300',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_63',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mccb_80',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mvtic_150',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='mvtic_240',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_10a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_16a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_25a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_2a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_35a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_4a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_50a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_1_6a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_10a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_16a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_20a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_25a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_35a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='phase_3_50a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='progress',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='tic_2x10',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='tic_2x16',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='tic_3x70',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='tic_3x95',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_1000kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_100kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_160kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_200kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_250kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_315kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_400kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='trafo_630kva',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='xlpe_240',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='pengawasan',
            name='xlpe_300',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
