# Generated by Django 4.2.3 on 2023-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_keuangan_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaan',
            name='bagian',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
