# Generated by Django 4.2.3 on 2023-07-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_pengadaan_bagian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengadaan',
            name='basket',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='nomor_spk',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='tanggal_akhir',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='tanggal_mulai',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='uraian',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pengadaan',
            name='vendor',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
