# Generated by Django 4.2.3 on 2023-07-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_pengadaan_bagian_alter_pengadaan_basket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keuangan',
            name='nomor_spk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.pengadaan'),
        ),
    ]
