from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.
class Pengadaan(models.Model):
    nomor_spk = models.CharField(max_length=32, blank=True, null=True)
    bagian = models.CharField(max_length=32, blank=True, null=True)
    vendor = models.CharField(max_length=128, blank=True, null=True)
    tanggal_mulai = models.DateField(blank=True, null=True)
    tanggal_akhir = models.DateField(blank=True, null=True)
    uraian = models.CharField(max_length=128, blank=True, null=True)
    nilai = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    basket = models.CharField(max_length=16, blank=True, null=True)
    status_approval = models.BooleanField(default=False, null=True)
    status_bayar = models.CharField(max_length=8, blank=True, null=True)


class Keuangan(models.Model):
    nomor_spk = models.ForeignKey(Pengadaan, on_delete=models.CASCADE)
    pembayaran = models.CharField(max_length=64)
    nilai = models.DecimalField(max_digits=15, decimal_places=2)
    tanggal_pembayaran = models.DateField()
    keterangan = models.CharField(max_length=128, blank=True)


class Amandemen(models.Model):
    nomor_spk = models.ForeignKey(Pengadaan, on_delete=models.CASCADE)
    nomor_amandemen = models.CharField(max_length=32)
    uraian = models.CharField(max_length=128)
    tanggal_amandemen = models.DateField()


class Pengawasan(models.Model):
    nomor_spk = models.ForeignKey(Pengadaan, on_delete=models.CASCADE)
    progress = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    a3c_150 = models.CharField(max_length=8, default=0)
    a3c_240 = models.CharField(max_length=8, default=0)
    mvtic_150 = models.CharField(max_length=8, default=0)
    mvtic_240 = models.CharField(max_length=8, default=0)
    xlpe_240 = models.CharField(max_length=8, default=0)
    xlpe_300 = models.CharField(max_length=8, default=0)
    trafo_100kva = models.CharField(max_length=8, default=0)
    trafo_160kva = models.CharField(max_length=8, default=0)
    trafo_200kva = models.CharField(max_length=8, default=0)
    trafo_250kva = models.CharField(max_length=8, default=0)
    trafo_315kva = models.CharField(max_length=8, default=0)
    trafo_400kva = models.CharField(max_length=8, default=0)
    trafo_630kva = models.CharField(max_length=8, default=0)
    trafo_1000kva = models.CharField(max_length=8, default=0)
    jtr_rak_tr = models.CharField(max_length=8, default=0)
    jtr_sktr = models.CharField(max_length=8, default=0)
    tic_3x70 = models.CharField(max_length=8, default=0)
    tic_3x95 = models.CharField(max_length=8, default=0)
    tic_2x10 = models.CharField(max_length=8, default=0)
    tic_2x16 = models.CharField(max_length=8, default=0)
    air_insulated_lbs = models.CharField(max_length=8)
    air_insulated_pb = models.CharField(max_length=8, default=0)
    air_insulated_cbom = models.CharField(max_length=8, default=0)
    fully_insulated_lbs = models.CharField(max_length=8, default=0)
    fully_insulated_pb = models.CharField(max_length=8, default=0)
    fully_insulated_cbom = models.CharField(max_length=8, default=0)
    kubikel_gi_incoming = models.CharField(max_length=8, default=0)
    kubikel_gi_kopel = models.CharField(max_length=8, default=0)
    kubikel_gi_outgoing = models.CharField(max_length=8, default=0)
    kubikel_gi_riser = models.CharField(max_length=8, default=0)
    kubikel_gi_cell_vt = models.CharField(max_length=8, default=0)
    kubikel_gi_ps = models.CharField(max_length=8, default=0)
    kwh_1_phase_prabayar = models.CharField(max_length=8, default=0)
    kwh_1_phase_reguler = models.CharField(max_length=8, default=0)
    kwh_elektrik_3_phase_kecil = models.CharField(max_length=8, default=0)
    kwh_amr_3_phase_besar = models.CharField(max_length=8, default=0)
    kwh_amr_3_phase_tm = models.CharField(max_length=8, default=0)
    phase_1_2a = models.PositiveIntegerField(default=0)
    phase_1_4a = models.PositiveIntegerField(default=0)
    phase_1_6a = models.PositiveIntegerField(default=0)
    phase_1_10a = models.PositiveIntegerField(default=0)
    phase_1_16a = models.PositiveIntegerField(default=0)
    phase_1_25a = models.PositiveIntegerField(default=0)
    phase_1_35a = models.PositiveIntegerField(default=0)
    phase_1_50a = models.PositiveIntegerField(default=0)
    phase_3_10a = models.PositiveIntegerField(default=0)
    phase_3_16a = models.PositiveIntegerField(default=0)
    phase_3_20a = models.PositiveIntegerField(default=0)
    phase_3_25a = models.PositiveIntegerField(default=0)
    phase_3_35a = models.PositiveIntegerField(default=0)
    phase_3_50a = models.PositiveIntegerField(default=0)
    mccb_63 = models.PositiveIntegerField(default=0)
    mccb_80 = models.PositiveIntegerField(default=0)
    mccb_100 = models.PositiveIntegerField(default=0)
    mccb_150 = models.PositiveIntegerField(default=0)
    mccb_200 = models.PositiveIntegerField(default=0)
    mccb_250 = models.PositiveIntegerField(default=0)
    mccb_300 = models.PositiveIntegerField(default=0)
    keterangan = models.CharField(max_length=128)
    rencana_bayar = models.DateField()